"""Compact control tables (refresh on rise off | on when they differ) -> ../controls_tables.md"""
import json
import os

H = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
V = ["A", "C3m", "C3d06", "C3d10", "C1", "C2", "C2f10", "C2f50", "C4a", "C4b", "C4c", "C4d", "C4e", "C4f", "B1", "B2"]
cases = ["states_128", "states_256", "states_512", "states_mr_128", "horiz_256", "tang_256", "tilt_256",
         "districts_256", "districts_512", "counties_256", "counties_512"]
out = ["# Control tables (generated by scripts/control_table.py)", "",
       "Columns: iterations, recomputes, cost, mean %, max %, invalid polygons, rises below score 20, status "
       "(c converged, s stalled, x iteration limit). Where refresh on rise off and on differ the cell reads off / on.", ""]


def cells(r):
    cost = r["it"] + r["rec"] * r["ratio"] if r.get("ratio") else float("nan")
    st = {"converged": "c", "stalled": "s"}.get(r["status"], "x")
    return [str(r["it"]), str(r["rec"]), f"{cost:.0f}", f"{100 * r['mean']:.2f}", f"{100 * r['max']:.1f}",
            str(r["invalid"]), str(r["rises20"]), st]


for c in cases:
    p = f"{H}/data/{c}.json"
    if not os.path.exists(p):
        continue
    d = json.load(open(p))
    out += [f"## {c}", "", "| variant | dt | it | rec | cost | mean % | max % | invalid | rises | status |",
            "|---|---|---|---|---|---|---|---|---|---|"]
    for v in V:
        off, on = d.get(f"{v}|off"), d.get(f"{v}|on")
        if not (off and off["score"]) and not (on and on["score"]):
            continue
        a = cells(off) if off and off["score"] else None
        b = cells(on) if on and on["score"] else None
        if a and b:
            row = [x if x == y else f"{x} / {y}" for x, y in zip(a, b)]
        else:
            row = a or b
        dt = (on or off).get("dt_used", "")
        dt = f"{dt:.2f}" if isinstance(dt, float) else str(dt)
        out.append(f"| {v} | {dt} | " + " | ".join(row) + " |")
    out.append("")
open(f"{H}/controls_tables.md", "w").write("\n".join(out))
print("\n".join(out))
